# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://www.liesauer.net/yogurt/subscribe?ACCESS_TOKEN=DAYxR3mMaZAsaqUb
- type: subscribe
  options:
    url: https://qxzy.top/tool.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/cdp2020/v2ray/master/README.md
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/eycorsican/rule-sets/master/kitsunebi_sub
- type: subscribe
  options:
    url: http://ssr.kanter.cn/dxxzst
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/voken100g/AutoSSR/master/recent
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/voken100g/AutoSSR/master/stable
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/voken100g/AutoSSR/master/online
- type: subscribe
  options:
    url: https://tudog-rss.com/link/n4FSTOL1pJYXpJjQ?sub=3
- type: subscribe
  options:
    url: https://iwxf.netlify.app/
- type: subscribe
  options:
    url: https://jiang.netlify.app/
- type: subscribe
  options:
    url: https://youlianboshi.netlify.app/
- type: subscribe
  options:
    url: https://prom-php.herokuapp.com/cloudfra_ssr.txt

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html
- type: webfuzz
  options:
    url: https://view.freev2ray.org
- type: webfuzz
  options:
    url: https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7
- type: webfuzz
  options:
    url: https://github.com/Alvin9999/new-pac/wiki/v2ray%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7
- type: webfuzz
  options:
    url: https://zfjvpn.gitbook.io/123/
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/README.md
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/umelabs/node.umelabs.dev/master/README.md
- type: webfuzz
  options:
    url: https://free-ss.site

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200
- type: tgchannel
  options:
    channel: ssList
    num: 200
- type: tgchannel
  options:
    channel: ssrshares
    num: 200
- type: tgchannel
  options:
    channel: V2List
    num: 200
- type: tgchannel
  options:
    channel: ShadowsocksRssr
    num: 200
- type: tgchannel
  options:
    channel: freeshadowsock
    num: 200
- type: tgchannel
  options:
    channel: baipiaojiedian
    num: 200
- type: tgchannel
  options:
    channel: ShareCentre
    num: 200
- type: tgchannel
  options:
    channel: FreeResources101
    num: 200
- type: tgchannel
  options:
    channel: Freedom_SSR
    num: 200
- type: tgchannel
  options:
    channel: VSshit
    num: 200
- type: tgchannel
  options:
    channel: free_v2ray_2020
    num: 200
- type: tgchannel
  options:
    channel: lRANSSR
    num: 200
- type: tgchannel
  options:
    channel: dangzhibu
    num: 200
- type: tgchannel
  options:
    channel: songssr
    num: 200
- type: tgchannel
  options:
    channel: ivmess
    num: 200
- type: tgchannel
  options:
    channel: CloudLinkChannel
    num: 200
- type: tgchannel
  options:
    channel: gouwu
    num: 200
- type: tgchannel
  options:
    channel: SSRSUB
    num: 200

# 翻墙党论坛抓取
# - type: web-fanqiangdang
#   options:
#     url: https://fanqiangdang.com/forum-48-1.html
# - type: web-fanqiangdang
#   options:
#     url: https://fanqiangdang.com/forum-2-1.html
# - type: web-fanqiangdang
#   options:
#     url: https://fanqiangdang.com/forum-36-1.html
# - type: web-fanqiangdang
#   options:
#     url: https://fanqiangdang.com/forum-50-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml
- type: clash
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/Clash.yml
- type: clash
  options:
    url: http://ops.dosec.cn/directlink/ss/asia.yaml
- type: clash
  options:
    url: http://ops.dosec.cn/directlink/ss/100Mb.yaml

# 某个网站抓取
- type: web-freessrxyz
  options:
