# 从网页模糊抓取订阅链接,并抓取每个订阅链接中的代理
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list
- type: webfuzzsub
  options:
    url: https://merlinblog.xyz/wiki/freess.html
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/README.md
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/umelabs/node.umelabs.dev/master/README.md

# 从网页模糊抓取代理
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html
- type: webfuzz
  options:
    url: https://view.freev2ray.org
- type: webfuzz
  options:
    url: https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7
- type: webfuzz
  options:
    url: https://github.com/Alvin9999/new-pac/wiki/v2ray%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7
- type: webfuzz
  options:
    url: https://zfjvpn.gitbook.io/123/
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/README.md
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/umelabs/node.umelabs.dev/master/README.md
- type: webfuzz
  options:
    url: https://free-ss.site

# 从订阅链接抓取代理
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/cdp2020/v2ray/master/README.md
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/eycorsican/rule-sets/master/kitsunebi_sub
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/voken100g/AutoSSR/master/recent
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/voken100g/AutoSSR/master/stable
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/voken100g/AutoSSR/master/online
- type: subscribe
  options:
    url: https://iwxf.netlify.app/
- type: subscribe
  options:
    url: https://jiang.netlify.app/
- type: subscribe
  options:
    url: https://youlianboshi.netlify.app/
- type: subscribe
  options:
    url: https://prom-php.herokuapp.com/cloudfra_ssr.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/Jsnzkpg/Jsnzkpg/Jsnzkpg/Jsnzkpg
- type: subscribe
  options:
    url: https://raw.fastgit.org/freefq/free/master/v2

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml
- type: clash
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/Clash.yml
- type: clash
  options:
    url: http://ops.dosec.cn/directlink/ss/asia.yaml
- type: clash
  options:
    url: http://ops.dosec.cn/directlink/ss/100Mb.yaml
- type: clash
  options:
    url: https://cdn.jsdelivr.net/gh/ssrsub/ssr@master/Clash.yml
- type: clash
  options:
    url: https://free886.herokuapp.com/clash/proxies
- type: clash
  options:
    url: https://raw.githubusercontent.com/adiwzx/freenode/main/adispeed.yml
- type: clash
  options:
    url: https://raw.githubusercontent.com/AzadNetCH/Clash/main/AzadNet.yml
- type: clash
  options:
    url: https://sub.cm/6MCPG9r

# 从tg频道抓取代理
- type: tgchannel
  options:
    channel: ssrList
    num: 200
- type: tgchannel
  options:
    channel: ssList
    num: 200
- type: tgchannel
  options:
    channel: V2List
    num: 200
- type: tgchannel
  options:
    channel: freeshadowsock
    num: 200
- type: tgchannel
  options:
    channel: baipiaojiedian
    num: 200
- type: tgchannel
  options:
    channel: ShareCentre
    num: 200
- type: tgchannel
  options:
    channel: Freedom_SSR
    num: 200
- type: tgchannel
  options:
    channel: songssr
    num: 200
- type: tgchannel
  options:
    channel: SSRSUB
    num: 200
- type: tgchannel
  options:
    channel: bnganblog
    num: 200
- type: tgchannel
  options:
    channel: freev2rayssr
    num: 200
- type: tgchannel
  options:
    channel: free_proxy_001
    num: 200
- type: tgchannel
  options:
    channel: zerobaipiao
    num: 200
- type: tgchannel
  options:
    channel: freebaipiao
    num: 200
- type: tgchannel
  options:
    channel: JiedianSsr
    num: 200
- type: tgchannel
  options:
    channel: FreeV2rays
    num: 200

# 翻墙党论坛抓取
# - type: web-fanqiangdang
#   options:
#     url: https://fanqiangdang.com/forum-48-1.html
# - type: web-fanqiangdang
#   options:
#     url: https://fanqiangdang.com/forum-2-1.html
# - type: web-fanqiangdang
#   options:
#     url: https://fanqiangdang.com/forum-36-1.html
# - type: web-fanqiangdang
#   options:
#     url: https://fanqiangdang.com/forum-50-1.html

# 从整个网站抓取
# - type: web-freessrxyz
#   options:
